-- AutoLancer leads migration
-- Source of truth: lib/lead-schema.js
-- Scope: leads table only. Future AI, proposal, invoice, payment, upload, and
-- user-auth fields remain out of this table until those product surfaces exist.

create extension if not exists pgcrypto;

create table if not exists public.leads (
  -- Internal database identity. External systems should use lead_id instead.
  id uuid primary key default gen_random_uuid(),

  -- Public-safe lead identifier generated by the application contract.
  lead_id text not null,

  -- The frontend contract sends these timestamps; defaults protect direct SQL
  -- inserts and server-side retries.
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  full_name text not null,
  email text not null,
  phone text,

  project_type text not null,
  project_type_value text not null,
  budget_range text not null,
  budget_range_value text not null,
  timeline text not null,
  timeline_value text not null,
  source text,
  source_value text,

  description text not null,
  existing_tools text,
  website_url text,

  intake_channel text not null default 'Web Form',
  intake_channel_value text not null default 'web_form',
  status text not null default 'new',
  n8n_status text not null default 'pending',

  -- Operational fields used by the server-side n8n handoff function after the
  -- public lead insert has already succeeded.
  n8n_last_error text,
  n8n_delivered_at timestamptz,

  constraint leads_lead_id_unique unique (lead_id),

  constraint leads_lead_id_length check (char_length(trim(lead_id)) between 12 and 80),
  constraint leads_full_name_length check (char_length(trim(full_name)) between 2 and 160),
  constraint leads_email_length check (char_length(trim(email)) between 5 and 254),
  constraint leads_phone_length check (phone is null or char_length(trim(phone)) between 7 and 32),
  constraint leads_description_length check (char_length(trim(description)) between 20 and 5000),
  constraint leads_existing_tools_length check (existing_tools is null or char_length(trim(existing_tools)) <= 1000),
  constraint leads_website_url_length check (website_url is null or char_length(trim(website_url)) <= 2048),
  constraint leads_intake_channel_length check (char_length(trim(intake_channel)) between 3 and 80),

  constraint leads_lead_id_format check (lead_id ~ '^lead_[0-9]{14}_[A-Za-z0-9-]{4,}$'),
  constraint leads_email_normalized check (email = lower(trim(email))),
  constraint leads_email_format check (email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]{2,}$'),
  constraint leads_phone_format check (phone is null or phone ~ '^\+?[1-9][0-9]{6,14}$'),
  constraint leads_website_url_format check (website_url is null or website_url ~* '^https?://[^[:space:]/$.?#].[^[:space:]]*$'),

  constraint leads_project_type_check check (project_type in (
    'Automation / workflow',
    'Website / web app',
    'Chatbot / AI assistant',
    'API / integration',
    'Other'
  )),
  constraint leads_project_type_value_check check (project_type_value in (
    'automation',
    'web_development',
    'chatbot',
    'integration',
    'other'
  )),
  constraint leads_budget_range_check check (budget_range in (
    'Under $500',
    '$500 - $1,000',
    '$1,000 - $3,000',
    '$3,000+'
  )),
  constraint leads_budget_range_value_check check (budget_range_value in (
    'under_500',
    '500_1000',
    '1000_3000',
    '3000_plus'
  )),
  constraint leads_timeline_check check (timeline in (
    'Within 1 week',
    'Within 2 weeks',
    'Within 1 month',
    'Flexible / no rush'
  )),
  constraint leads_timeline_value_check check (timeline_value in (
    '1_week',
    '2_weeks',
    '1_month',
    'flexible'
  )),
  constraint leads_source_check check (source is null or source in (
    'LinkedIn',
    'Referral',
    'Twitter / X',
    'Google search',
    'Other'
  )),
  constraint leads_source_value_check check (source_value is null or source_value in (
    'linkedin',
    'referral',
    'twitter',
    'google',
    'other'
  )),
  constraint leads_intake_channel_check check (intake_channel = 'Web Form'),
  constraint leads_intake_channel_value_check check (intake_channel_value = 'web_form'),
  constraint leads_project_type_pair_check check (
    (project_type = 'Automation / workflow' and project_type_value = 'automation')
    or (project_type = 'Website / web app' and project_type_value = 'web_development')
    or (project_type = 'Chatbot / AI assistant' and project_type_value = 'chatbot')
    or (project_type = 'API / integration' and project_type_value = 'integration')
    or (project_type = 'Other' and project_type_value = 'other')
  ),
  constraint leads_budget_range_pair_check check (
    (budget_range = 'Under $500' and budget_range_value = 'under_500')
    or (budget_range = '$500 - $1,000' and budget_range_value = '500_1000')
    or (budget_range = '$1,000 - $3,000' and budget_range_value = '1000_3000')
    or (budget_range = '$3,000+' and budget_range_value = '3000_plus')
  ),
  constraint leads_timeline_pair_check check (
    (timeline = 'Within 1 week' and timeline_value = '1_week')
    or (timeline = 'Within 2 weeks' and timeline_value = '2_weeks')
    or (timeline = 'Within 1 month' and timeline_value = '1_month')
    or (timeline = 'Flexible / no rush' and timeline_value = 'flexible')
  ),
  constraint leads_source_pair_check check (
    (source is null and source_value is null)
    or (source = 'LinkedIn' and source_value = 'linkedin')
    or (source = 'Referral' and source_value = 'referral')
    or (source = 'Twitter / X' and source_value = 'twitter')
    or (source = 'Google search' and source_value = 'google')
    or (source = 'Other' and source_value = 'other')
  )),
  constraint leads_status_check check (status in (
    'new',
    'qualified',
    'proposal_pending',
    'proposal_sent',
    'accepted',
    'invoiced',
    'paid',
    'archived'
  )),
  constraint leads_n8n_status_check check (n8n_status in (
    'pending',
    'delivered',
    'failed'
  )),

  constraint leads_n8n_delivery_state check (
    (n8n_status = 'delivered' and n8n_delivered_at is not null and n8n_last_error is null)
    or (n8n_status = 'failed' and n8n_last_error is not null)
    or (n8n_status = 'pending' and n8n_delivered_at is null)
  )
);

create or replace function public.set_current_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_leads_updated_at on public.leads;

create trigger set_leads_updated_at
before update on public.leads
for each row
execute function public.set_current_updated_at();

create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_status_idx on public.leads (status);
create index if not exists leads_email_idx on public.leads (email);
create index if not exists leads_project_type_idx on public.leads (project_type);
create index if not exists leads_project_type_value_idx on public.leads (project_type_value);
create index if not exists leads_n8n_status_idx on public.leads (n8n_status);
create index if not exists leads_status_created_at_idx on public.leads (status, created_at desc);
create index if not exists leads_n8n_status_created_at_idx on public.leads (n8n_status, created_at desc);

alter table public.leads enable row level security;

revoke all on table public.leads from anon, authenticated;
grant usage on schema public to anon;

-- Public web visitors can only create a fresh lead. They cannot submit
-- operational n8n fields, read leads, update leads, or delete leads.
grant insert (
  lead_id,
  created_at,
  updated_at,
  full_name,
  email,
  phone,
  project_type,
  project_type_value,
  budget_range,
  budget_range_value,
  timeline,
  timeline_value,
  source,
  source_value,
  description,
  existing_tools,
  website_url,
  intake_channel,
  intake_channel_value,
  status,
  n8n_status
) on table public.leads to anon;

drop policy if exists "Public can submit lead intake records" on public.leads;

create policy "Public can submit lead intake records"
on public.leads
for insert
to anon
with check (
  intake_channel = 'Web Form'
  and intake_channel_value = 'web_form'
  and status = 'new'
  and n8n_status = 'pending'
  and n8n_last_error is null
  and n8n_delivered_at is null
);

comment on table public.leads is
  'AutoLancer project intake leads. Public clients can insert only; reads and status updates stay server-side.';

comment on column public.leads.lead_id is
  'Public-safe lead identifier generated by lib/lead-schema.js and used across Supabase and n8n.';

comment on column public.leads.n8n_status is
  'Server-updated handoff state for the n8n automation pipeline.';
